### ISSUE TITLE
Store prop being updated accidentally

### ISSUE THREAD

**Issue by daninacca** [piniajs/vue-3-cli-webpack-4#50]
So I found out that if I do an Object.assign with a state property as the target it will update the state without there being any action called. I even managed to accidentally update the state from a child component that had a state property as its component-prop, which i was doing an Object.assign over to emit the copied data, interestingly the Object.assign managed to override the component prop value and even the state property that it originated from. I've done a simpler example of it here:
https://stackblitz.com/edit/github-ev9fpm-2wgbsa?file=src%2FApp.vue,src%2Fstores%2Fcounter.ts

The store prop is being updated when u click the button by an Object.assign call in the template. But yea you can even update props with this loophole so mb check that out as well.

Thank you and good luck,
Dani

**Comment by posva** [comment]
Thanks, this is just how Object.assign works. The prop behavior is documented in vue docs.
